local M = {}

function M.get(p)
	return {
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg, bg = p.bg },
		NormalFloat = { fg = p.fg, bg = p.float_bg },
		FloatBorder = { fg = p.border, bg = p.float_bg },
		FloatTitle = { fg = p.ui_accent, bg = p.float_bg, bold = true },
		FloatFooter = { fg = p.grey, bg = p.float_bg },
		FloatShadow = { bg = p.bg_alt, blend = 80 },
		FloatShadowThrough = { bg = p.bg_alt, blend = 100 },

		Bold = { bold = true },
		Italic = { italic = true },
		Underlined = { underline = true },
		Cursor = { fg = p.bg, bg = p.fg },
		CursorIM = { fg = p.bg, bg = p.ui_accent },
		lCursor = { fg = p.bg, bg = p.ui_accent },
		CursorLine = { bg = p.bg_soft },
		CursorColumn = { bg = p.bg_soft },
		CursorLineNr = { fg = p.ui_accent, bg = p.bg_soft, bold = true },
		CursorLineFold = { fg = p.grey_light, bg = p.bg_soft },
		CursorLineSign = { bg = p.bg_soft },

		LineNr = { fg = p.line_number },
		LineNrAbove = { link = "LineNr" },
		LineNrBelow = { link = "LineNr" },
		SignColumn = { fg = p.line_number, bg = p.bg },
		FoldColumn = { fg = p.grey, bg = p.bg },
		Folded = { fg = p.grey_light, bg = p.surface },
		ColorColumn = { bg = p.surface },
		EndOfBuffer = { fg = p.special },
		NonText = { fg = p.special },
		Whitespace = { fg = p.special },
		SpecialKey = { fg = p.special },
		Conceal = { fg = p.grey },

		WinBar = { fg = p.grey_light, bg = p.bg_alt, bold = true },
		WinBarNC = { fg = p.grey, bg = p.bg_alt },
		WinSeparator = { fg = p.border, bg = p.bg },
		VertSplit = { link = "WinSeparator" },

		Search = { fg = p.bg, bg = p.warning },
		CurSearch = { fg = p.bg, bg = p.ui_accent, bold = true },
		IncSearch = { link = "CurSearch" },
		Substitute = { fg = p.bg, bg = p.error },
		MatchParen = { fg = p.ui_accent, bg = p.visual, bold = true },
		Visual = { bg = p.visual },
		VisualNOS = { bg = p.visual },
		QuickFixLine = { bg = p.bg_soft, bold = true },

		Pmenu = { fg = p.fg, bg = p.float_bg },
		PmenuSel = { fg = p.fg_bright, bg = p.selection, bold = true },
		PmenuKind = { fg = p.type, bg = p.float_bg },
		PmenuKindSel = { fg = p.type, bg = p.selection, bold = true },
		PmenuExtra = { fg = p.grey, bg = p.float_bg },
		PmenuExtraSel = { fg = p.grey_light, bg = p.selection },
		PmenuMatch = { fg = p.keyword, bg = p.float_bg, bold = true },
		PmenuMatchSel = { fg = p.keyword, bg = p.selection, bold = true },
		PmenuSbar = { bg = p.float_bg },
		PmenuThumb = { bg = p.scrollbar },
		WildMenu = { fg = p.fg_bright, bg = p.selection, bold = true },

		StatusLine = { fg = p.fg, bg = p.bg_alt },
		StatusLineNC = { fg = p.grey, bg = p.bg_alt },
		StatusLineTerm = { link = "StatusLine" },
		StatusLineTermNC = { link = "StatusLineNC" },
		TabLineFill = { bg = p.bg_alt },
		TabLine = { fg = p.grey, bg = p.bg_alt },
		TabLineSel = { fg = p.fg_bright, bg = p.bg, bold = true },

		MsgArea = { fg = p.fg, bg = p.bg },
		MsgSeparator = { fg = p.border, bg = p.bg_alt },
		ModeMsg = { fg = p.fg_bright, bold = true },
		MoreMsg = { fg = p.info },
		Question = { fg = p.ui_accent },
		ErrorMsg = { fg = p.error, bold = true },
		WarningMsg = { fg = p.warning },
		PopupNotification = { link = "WarningMsg" },

		Title = { fg = p.link, bold = true },
		Directory = { fg = p.func },
		Tag = { fg = p.link, bold = true },
		ToolbarButton = { fg = p.bg, bg = p.ui_accent, bold = true },
		ToolbarLine = { bg = p.surface },

		Added = { fg = p.git_add },
		Changed = { fg = p.git_change },
		Removed = { fg = p.git_delete },
		DiffAdd = { bg = p.diff_add },
		DiffChange = { bg = p.diff_change },
		DiffDelete = { bg = p.diff_delete },
		DiffText = { bg = p.selection, bold = true },

		SpellBad = { sp = p.error, undercurl = true },
		SpellCap = { sp = p.info, undercurl = true },
		SpellLocal = { sp = p.hint, undercurl = true },
		SpellRare = { sp = p.warning, undercurl = true },

		qfFileName = { fg = p.func },
		qfLineNr = { fg = p.number },
		debugPC = { bg = p.bg_soft },
		debugBreakpoint = { fg = p.error, bg = p.bg_soft },
		Terminal = { link = "Normal" },
	}
end

return M
