local M = {}

function M.get(p)
	return {
		BlinkCmpMenu = { fg = p.limestone, bg = p.quench_dark },
		BlinkCmpMenuBorder = { fg = p.quench_edge, bg = p.quench_dark },
		BlinkCmpMenuSelection = { bg = p.quench_bright, bold = true },
		BlinkCmpScrollBarThumb = { bg = p.quench_mid },
		BlinkCmpScrollBarGutter = {},
		BlinkCmpLabel = { fg = p.limestone },
		BlinkCmpLabelMatch = { fg = p.cobalt, bold = true },
		BlinkCmpLabelDeprecated = { fg = p.slag, strikethrough = true },
		BlinkCmpLabelDetail = { fg = p.tarnish },
		BlinkCmpLabelDescription = { fg = p.tarnish },
		BlinkCmpSource = { fg = p.slag },
		BlinkCmpGhostText = { fg = p.special },
		BlinkCmpDoc = { fg = p.limestone, bg = p.quench_dark },
		BlinkCmpDocBorder = { fg = p.quench_edge, bg = p.quench_dark },
		BlinkCmpDocSeparator = { fg = p.smelt, bg = p.quench_dark },
		BlinkCmpDocCursorLine = { bg = p.temper },
		BlinkCmpSignatureHelp = { fg = p.limestone, bg = p.quench_dark },
		BlinkCmpSignatureHelpBorder = { fg = p.quench_edge, bg = p.quench_dark },
		BlinkCmpSignatureHelpActiveParameter = { fg = p.copper, bold = true },
		BlinkCmpKind = { fg = p.copper },
		BlinkCmpKindUnknown = { fg = p.copper },
		BlinkCmpKindFunction = { fg = p.cobalt },
		BlinkCmpKindMethod = { fg = p.cobalt },
		BlinkCmpKindConstructor = { fg = p.patina },
		BlinkCmpKindClass = { fg = p.patina },
		BlinkCmpKindInterface = { fg = p.patina },
		BlinkCmpKindStruct = { fg = p.patina },
		BlinkCmpKindEnum = { fg = p.patina },
		BlinkCmpKindTypeParameter = { fg = p.patina },
		BlinkCmpKindVariable = { fg = p.limestone },
		BlinkCmpKindText = { fg = p.limestone },
		BlinkCmpKindModule = { fg = p.patina },
		BlinkCmpKindConstant = { fg = p.ember },
		BlinkCmpKindValue = { fg = p.ember },
		BlinkCmpKindEnumMember = { fg = p.ember },
		BlinkCmpKindKeyword = { fg = p.oxidized },
		BlinkCmpKindEvent = { fg = p.oxidized },
		BlinkCmpKindOperator = { fg = p.slag },
		BlinkCmpKindProperty = { fg = p.limestone },
		BlinkCmpKindField = { fg = p.limestone },
		BlinkCmpKindSnippet = { fg = p.patina },
		BlinkCmpKindFile = { fg = p.cobalt },
		BlinkCmpKindFolder = { fg = p.cobalt },
		BlinkCmpKindColor = { fg = p.ember },
		BlinkCmpKindReference = { fg = p.ember },
		BlinkCmpKindUnit = { fg = p.cobalt },
	}
end

return M
