local M = {}

function M.get(p)
	return {
		FzfLuaNormal = { fg = p.fg, bg = p.float_bg },
		FzfLuaBorder = { fg = p.border, bg = p.float_bg },
		FzfLuaTitle = { fg = p.ui_accent, bg = p.float_bg, bold = true },
		FzfLuaTitleFlags = { fg = p.grey_light, bg = p.float_bg },
		FzfLuaBackdrop = { bg = p.bg },
		FzfLuaHelpNormal = { link = "FzfLuaNormal" },
		FzfLuaHelpBorder = { link = "FzfLuaBorder" },
		FzfLuaPreviewNormal = { fg = p.fg, bg = p.float_bg },
		FzfLuaPreviewBorder = { fg = p.border, bg = p.float_bg },
		FzfLuaPreviewTitle = { fg = p.ui_accent, bg = p.float_bg, bold = true },
		FzfLuaCursor = { link = "Cursor" },
		FzfLuaCursorLine = { bg = p.selection },
		FzfLuaCursorLineNr = { fg = p.ui_accent, bg = p.selection, bold = true },
		FzfLuaSearch = { link = "IncSearch" },
		FzfLuaScrollBorderEmpty = { link = "FzfLuaBorder" },
		FzfLuaScrollBorderFull = { fg = p.grey_light },
		FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
		FzfLuaScrollFloatFull = { bg = p.scrollbar },
		FzfLuaDirIcon = { link = "Directory" },
		FzfLuaDirPart = { fg = p.grey_mid },
		FzfLuaFilePart = { fg = p.fg },
		FzfLuaHeaderBind = { fg = p.ui_accent },
		FzfLuaHeaderText = { fg = p.grey_light },
		FzfLuaPathColNr = { fg = p.grey_mid },
		FzfLuaPathLineNr = { fg = p.grey },
		FzfLuaLivePrompt = { fg = p.ui_accent },
		FzfLuaLiveSym = { fg = p.ui_accent },
		FzfLuaBufId = { fg = p.grey_mid },
		FzfLuaBufName = { link = "Directory" },
		FzfLuaBufLineNr = { link = "LineNr" },
		FzfLuaBufNr = { fg = p.grey_light },
		FzfLuaBufFlagCur = { fg = p.ui_accent },
		FzfLuaBufFlagAlt = { fg = p.signal },
		FzfLuaTabTitle = { fg = p.ui_accent, bold = true },
		FzfLuaTabMarker = { fg = p.ok, bold = true },
		FzfLuaCmdEx = { link = "Statement" },
		FzfLuaCmdBuf = { link = "Added" },
		FzfLuaCmdGlobal = { link = "Directory" },
		FzfLuaFzfNormal = { fg = p.grey_mid, bg = p.float_bg },
		FzfLuaFzfCursorLine = { fg = p.fg, bg = p.selection, bold = true },
		FzfLuaFzfMatch = { fg = p.ui_accent, bold = true },
		FzfLuaFzfBorder = { link = "FzfLuaBorder" },
		FzfLuaFzfScrollbar = { fg = p.grey_light },
		FzfLuaFzfSeparator = { link = "FzfLuaBorder" },
		FzfLuaFzfGutter = { link = "FzfLuaNormal" },
		FzfLuaFzfHeader = { link = "FzfLuaTitle" },
		FzfLuaFzfInfo = { fg = p.grey_mid },
		FzfLuaFzfPointer = { fg = p.ui_accent },
		FzfLuaFzfMarker = { fg = p.ok },
		FzfLuaFzfSpinner = { fg = p.ui_accent },
		FzfLuaFzfPrompt = { fg = p.ui_accent },
		FzfLuaFzfQuery = { fg = p.fg },
	}
end

return M
