local M = {}

function M.get(p)
	return {
		FzfLuaNormal = { fg = p.limestone, bg = p.quench_dark },
		FzfLuaBorder = { fg = p.quench_edge, bg = p.quench_dark },
		FzfLuaTitle = { fg = p.copper, bg = p.quench_dark, bold = true },
		FzfLuaTitleFlags = { fg = p.tarnish, bg = p.quench_dark },
		FzfLuaBackdrop = { bg = p.void },
		FzfLuaHelpNormal = { link = "FzfLuaNormal" },
		FzfLuaHelpBorder = { link = "FzfLuaBorder" },
		FzfLuaPreviewNormal = { fg = p.limestone, bg = p.quench_dark },
		FzfLuaPreviewBorder = { fg = p.quench_edge, bg = p.quench_dark },
		FzfLuaPreviewTitle = { fg = p.copper, bg = p.quench_dark, bold = true },
		FzfLuaCursor = { link = "Cursor" },
		FzfLuaCursorLine = { bg = p.quench_bright },
		FzfLuaCursorLineNr = { fg = p.copper, bg = p.quench_bright, bold = true },
		FzfLuaSearch = { link = "IncSearch" },
		FzfLuaScrollBorderEmpty = { link = "FzfLuaBorder" },
		FzfLuaScrollBorderFull = { link = "FzfLuaBorder" },
		FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
		FzfLuaScrollFloatFull = { bg = p.quench_mid },
		FzfLuaDirIcon = { link = "Directory" },
		FzfLuaDirPart = { fg = p.slag },
		FzfLuaFilePart = { fg = p.limestone },
		FzfLuaHeaderBind = { fg = p.copper },
		FzfLuaHeaderText = { fg = p.copper },
		FzfLuaPathColNr = { fg = p.patina },
		FzfLuaPathLineNr = { fg = p.verdigris },
		FzfLuaLivePrompt = { fg = p.copper },
		FzfLuaLiveSym = { fg = p.copper },
		FzfLuaBufId = { fg = p.slag },
		FzfLuaBufName = { link = "Directory" },
		FzfLuaBufLineNr = { link = "LineNr" },
		FzfLuaBufNr = { fg = p.tarnish },
		FzfLuaBufFlagCur = { fg = p.copper },
		FzfLuaBufFlagAlt = { fg = p.cobalt },
		FzfLuaTabTitle = { fg = p.copper, bold = true },
		FzfLuaTabMarker = { fg = p.verdigris, bold = true },
		FzfLuaCmdEx = { link = "Statement" },
		FzfLuaCmdBuf = { link = "Added" },
		FzfLuaCmdGlobal = { link = "Directory" },
		FzfLuaFzfNormal = { fg = p.slag, bg = p.quench_dark },
		FzfLuaFzfCursorLine = { fg = p.limestone, bg = p.quench_bright, bold = true },
		FzfLuaFzfMatch = { fg = p.cobalt, bold = true },
		FzfLuaFzfBorder = { link = "FzfLuaBorder" },
		FzfLuaFzfScrollbar = { link = "FzfLuaBorder" },
		FzfLuaFzfSeparator = { link = "FzfLuaBorder" },
		FzfLuaFzfGutter = { link = "FzfLuaNormal" },
		FzfLuaFzfHeader = { link = "FzfLuaTitle" },
		FzfLuaFzfInfo = { fg = p.slag },
		FzfLuaFzfPointer = { fg = p.copper },
		FzfLuaFzfMarker = { fg = p.verdigris },
		FzfLuaFzfSpinner = { fg = p.copper },
		FzfLuaFzfPrompt = { fg = p.copper },
		FzfLuaFzfQuery = { fg = p.limestone },
	}
end

return M
