local M = {}

function M.get(p)
	return {
		MarkviewPalette0 = { fg = p.slag, bg = p.smelt },
		MarkviewPalette0Fg = { fg = p.slag },
		MarkviewPalette0Bg = { bg = p.smelt },
		MarkviewPalette0Sign = { fg = p.slag },
		MarkviewPalette1 = { fg = p.rust, bg = p.smelt },
		MarkviewPalette1Fg = { fg = p.rust },
		MarkviewPalette1Bg = { bg = p.smelt },
		MarkviewPalette1Sign = { fg = p.rust },
		MarkviewPalette2 = { fg = p.copper, bg = p.smelt },
		MarkviewPalette2Fg = { fg = p.copper },
		MarkviewPalette2Bg = { bg = p.smelt },
		MarkviewPalette2Sign = { fg = p.copper },
		MarkviewPalette3 = { fg = p.forge_amber, bg = p.smelt },
		MarkviewPalette3Fg = { fg = p.forge_amber },
		MarkviewPalette3Bg = { bg = p.smelt },
		MarkviewPalette3Sign = { fg = p.forge_amber },
		MarkviewPalette4 = { fg = p.verdigris, bg = p.smelt },
		MarkviewPalette4Fg = { fg = p.verdigris },
		MarkviewPalette4Bg = { bg = p.smelt },
		MarkviewPalette4Sign = { fg = p.verdigris },
		MarkviewPalette5 = { fg = p.cobalt, bg = p.smelt },
		MarkviewPalette5Fg = { fg = p.cobalt },
		MarkviewPalette5Bg = { bg = p.smelt },
		MarkviewPalette5Sign = { fg = p.cobalt },
		MarkviewPalette6 = { fg = p.patina, bg = p.smelt },
		MarkviewPalette6Fg = { fg = p.patina },
		MarkviewPalette6Bg = { bg = p.smelt },
		MarkviewPalette6Sign = { fg = p.patina },
		MarkviewPalette7 = { fg = p.oxidized, bg = p.smelt },
		MarkviewPalette7Fg = { fg = p.oxidized },
		MarkviewPalette7Bg = { bg = p.smelt },
		MarkviewPalette7Sign = { fg = p.oxidized },
		MarkviewHeading1 = { link = "MarkviewPalette1" },
		MarkviewHeading2 = { link = "MarkviewPalette2" },
		MarkviewHeading3 = { link = "MarkviewPalette3" },
		MarkviewHeading4 = { link = "MarkviewPalette4" },
		MarkviewHeading5 = { link = "MarkviewPalette5" },
		MarkviewHeading6 = { link = "MarkviewPalette6" },
		MarkviewHeading1Sign = { link = "MarkviewPalette1Sign" },
		MarkviewHeading2Sign = { link = "MarkviewPalette2Sign" },
		MarkviewHeading3Sign = { link = "MarkviewPalette3Sign" },
		MarkviewHeading4Sign = { link = "MarkviewPalette4Sign" },
		MarkviewHeading5Sign = { link = "MarkviewPalette5Sign" },
		MarkviewHeading6Sign = { link = "MarkviewPalette6Sign" },
		MarkviewCode = { bg = p.smelt },
		MarkviewCodeInfo = { fg = p.slag, bg = p.smelt },
		MarkviewCodeFg = { fg = p.smelt },
		MarkviewInlineCode = { bg = p.smelt },
		MarkviewBlockQuoteDefault = { link = "MarkviewPalette0Fg" },
		MarkviewBlockQuoteError = { link = "MarkviewPalette1Fg" },
		MarkviewBlockQuoteWarn = { link = "MarkviewPalette3Fg" },
		MarkviewBlockQuoteSpecial = { link = "MarkviewPalette6Fg" },
		MarkviewBlockQuoteOk = { link = "MarkviewPalette4Fg" },
		MarkviewBlockQuoteNote = { link = "MarkviewPalette5Fg" },
		MarkviewCheckboxCancelled = { link = "MarkviewPalette0Fg" },
		MarkviewCheckboxUnchecked = { link = "MarkviewPalette1Fg" },
		MarkviewCheckboxPending = { link = "MarkviewPalette2Fg" },
		MarkviewCheckboxChecked = { link = "MarkviewPalette4Fg" },
		MarkviewCheckboxProgress = { link = "MarkviewPalette6Fg" },
		MarkviewCheckboxStriked = { fg = p.slag, strikethrough = true },
		MarkviewListItemMinus = { link = "MarkviewPalette2Fg" },
		MarkviewListItemPlus = { link = "MarkviewPalette4Fg" },
		MarkviewListItemStar = { link = "MarkviewPalette6Fg" },
		MarkviewTableHeader = { link = "Title" },
		MarkviewTableBorder = { fg = p.slag },
		MarkviewTableAlignLeft = { fg = p.slag },
		MarkviewTableAlignCenter = { fg = p.slag },
		MarkviewTableAlignRight = { fg = p.slag },
		MarkviewHyperlink = { fg = p.cobalt, underline = true },
		MarkviewImage = { fg = p.cobalt, underline = true },
		MarkviewEmail = { fg = p.cobalt, underline = true },
		MarkviewSubscript = { link = "MarkviewPalette3Fg" },
		MarkviewSuperscript = { link = "MarkviewPalette6Fg" },
		MarkviewIcon0 = { fg = p.slag, bg = p.smelt },
		MarkviewIcon1 = { fg = p.rust, bg = p.smelt },
		MarkviewIcon2 = { fg = p.copper, bg = p.smelt },
		MarkviewIcon3 = { fg = p.forge_amber, bg = p.smelt },
		MarkviewIcon4 = { fg = p.verdigris, bg = p.smelt },
		MarkviewIcon5 = { fg = p.cobalt, bg = p.smelt },
		MarkviewIcon6 = { fg = p.patina, bg = p.smelt },
		MarkviewIcon3Fg = { link = "MarkviewPalette3Fg" },
		MarkviewSpecial = { link = "Special" },
		MarkviewComment = { link = "Comment" },
	}
end

return M
