local M = {}

function M.get(p)
	return {
		RenderMarkdownH1 = { link = "MarkviewPalette1Fg" },
		RenderMarkdownH2 = { link = "MarkviewPalette2Fg" },
		RenderMarkdownH3 = { link = "MarkviewPalette3Fg" },
		RenderMarkdownH4 = { link = "MarkviewPalette4Fg" },
		RenderMarkdownH5 = { link = "MarkviewPalette5Fg" },
		RenderMarkdownH6 = { link = "MarkviewPalette6Fg" },
		RenderMarkdownH1Bg = { link = "MarkviewPalette1Bg" },
		RenderMarkdownH2Bg = { link = "MarkviewPalette2Bg" },
		RenderMarkdownH3Bg = { link = "MarkviewPalette3Bg" },
		RenderMarkdownH4Bg = { link = "MarkviewPalette4Bg" },
		RenderMarkdownH5Bg = { link = "MarkviewPalette5Bg" },
		RenderMarkdownH6Bg = { link = "MarkviewPalette6Bg" },
		RenderMarkdownCode = { link = "MarkviewCode" },
		RenderMarkdownCodeInfo = { link = "MarkviewCodeInfo" },
		RenderMarkdownCodeBorder = { link = "MarkviewCode" },
		RenderMarkdownCodeFallback = { link = "Normal" },
		RenderMarkdownCodeInline = { link = "MarkviewInlineCode" },
		RenderMarkdownTableHead = { link = "MarkviewTableHeader" },
		RenderMarkdownTableRow = { link = "MarkviewTableBorder" },
		RenderMarkdownTableFill = { link = "Conceal" },
		RenderMarkdownLink = { link = "MarkviewHyperlink" },
		RenderMarkdownLinkTitle = { link = "MarkviewHyperlink" },
		RenderMarkdownWikiLink = { link = "MarkviewHyperlink" },
		RenderMarkdownUnchecked = { link = "MarkviewCheckboxUnchecked" },
		RenderMarkdownChecked = { link = "MarkviewCheckboxChecked" },
		RenderMarkdownTodo = { link = "MarkviewCheckboxPending" },
		RenderMarkdownQuote = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownQuote1 = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownQuote2 = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownQuote3 = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownQuote4 = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownQuote5 = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownQuote6 = { link = "MarkviewBlockQuoteDefault" },
		RenderMarkdownSuccess = { link = "MarkviewBlockQuoteOk" },
		RenderMarkdownInfo = { link = "MarkviewBlockQuoteNote" },
		RenderMarkdownHint = { link = "MarkviewBlockQuoteSpecial" },
		RenderMarkdownWarn = { link = "MarkviewBlockQuoteWarn" },
		RenderMarkdownError = { link = "MarkviewBlockQuoteError" },
		RenderMarkdownBullet = { link = "MarkviewListItemMinus" },
		RenderMarkdownDash = { link = "LineNr" },
		RenderMarkdownSign = { fg = p.slag },
		RenderMarkdownMath = { link = "MarkviewPalette3Fg" },
		RenderMarkdownIndent = { link = "Whitespace" },
		RenderMarkdownHtmlComment = { link = "Comment" },
		RenderMarkdownInlineHighlight = { link = "MarkviewInlineCode" },
	}
end

return M
