local M = {}

function M.get(p)
	return {
		RenderMarkdownH1 = { fg = p.link, bold = true },
		RenderMarkdownH2 = { fg = p.ui_accent, bold = true },
		RenderMarkdownH3 = { fg = p.func },
		RenderMarkdownH4 = { fg = p.type },
		RenderMarkdownH5 = { fg = p.constant },
		RenderMarkdownH6 = { fg = p.grey_light },
		RenderMarkdownH1Bg = { fg = p.link, bg = p.surface, bold = true },
		RenderMarkdownH2Bg = { fg = p.ui_accent, bg = p.surface, bold = true },
		RenderMarkdownH3Bg = { fg = p.func, bg = p.surface },
		RenderMarkdownH4Bg = { fg = p.type, bg = p.surface },
		RenderMarkdownH5Bg = { fg = p.constant, bg = p.surface },
		RenderMarkdownH6Bg = { fg = p.grey_light, bg = p.surface },
		RenderMarkdownCode = { bg = p.surface },
		RenderMarkdownCodeInfo = { fg = p.grey, bg = p.surface },
		RenderMarkdownCodeBorder = { fg = p.border, bg = p.surface },
		RenderMarkdownCodeFallback = { link = "Normal" },
		RenderMarkdownCodeInline = { fg = p.string, bg = p.surface },
		RenderMarkdownTableHead = { fg = p.silver },
		RenderMarkdownTableRow = { fg = p.fg },
		RenderMarkdownTableBorder = { fg = p.border },
		RenderMarkdownLink = { fg = p.link, underline = true },
		RenderMarkdownLinkTitle = { fg = p.grey_light },
		RenderMarkdownWikiLink = { fg = p.link },
		RenderMarkdownUnchecked = { link = "DiagnosticWarn" },
		RenderMarkdownChecked = { link = "DiagnosticOk" },
		RenderMarkdownTodo = { fg = p.ui_accent },
		RenderMarkdownQuote = { fg = p.grey_light },
		RenderMarkdownQuote1 = { fg = p.grey_pale },
		RenderMarkdownQuote2 = { fg = p.grey_light },
		RenderMarkdownQuote3 = { fg = p.grey },
		RenderMarkdownQuote4 = { fg = p.grey_mid },
		RenderMarkdownQuote5 = { fg = p.line_number },
		RenderMarkdownQuote6 = { fg = p.special },
		RenderMarkdownSuccess = { link = "DiagnosticOk" },
		RenderMarkdownInfo = { link = "DiagnosticInfo" },
		RenderMarkdownHint = { link = "DiagnosticHint" },
		RenderMarkdownWarn = { link = "DiagnosticWarn" },
		RenderMarkdownError = { link = "DiagnosticError" },
		RenderMarkdownBullet = { fg = p.ui_accent },
		RenderMarkdownDash = { fg = p.border },
		RenderMarkdownSign = { fg = p.line_number },
		RenderMarkdownMath = { link = "Special" },
		RenderMarkdownIndent = { link = "Whitespace" },
		RenderMarkdownHtmlComment = { link = "Comment" },
		RenderMarkdownInlineHighlight = { fg = p.fg, bg = p.visual },
	}
end

return M
